server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: [ "env", "health", "info", "refresh" ]

spring:
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.yml
    enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/first_project?useSSL=false
    username: root
    password: 'R@simgunay2018'
  jpa:
    open-in-view: true
    show-sql: true

hibernate:
  hbm2ddl:
    auto: create
